### ISSUE TITLE
About the dimension of input to bilstm

### ISSUE THREAD

**Issue by kenchan0226** [ExplorerFreda/Structured-Self-Attentive-Sentence-Embedding#6]
In line 43-44 of models.py,
`emb = self.drop(self.encoder(inp))`
`outp = self.bilstm(emb, hidden)[0]`
It directly supplies the embedding obtained from self.encoder as the input to self.bilstm.
However, the dimension of emb is (batch_size  * seq_len * embedding_dim), 
while the dimension of input to lstm is (seq_len * batch_size * embedding_dim).
Are there any problems? Thanks.

**Comment by hantek** [comment]
There is a `.t()` in the packing function, c.f., https://github.com/ExplorerFreda/Structured-Self-Attentive-Sentence-Embedding/blob/master/train.py#L43

So basically the `inp` shape is `(seq_len, batch_size, embedding_dim)`

**Comment by kenchan0226** [comment]
Thank you so much!
