### ISSUE TITLE
bool value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by ashusheng** [ExplorerFreda/Structured-Self-Attentive-Sentence-Embedding#8]
[https://github.com/ExplorerFreda/Structured-Self-Attentive-Sentence-Embedding/blob/8e0ace59ed6538d4f33d4a2af3222545c759d430/train.py#L81](https://github.com/ExplorerFreda/Structured-Self-Attentive-Sentence-Embedding/blob/8e0ace59ed6538d4f33d4a2af3222545c759d430/train.py#L81)
`if attention:` will raise the error as follow: 
`RuntimeError: bool value of Tensor with more than one value is ambiguous`
Can anyone help me? Please.

**Comment by ExplorerFreda** [comment]
Sorry for the late interaction. It should be caused by the different versions of PyTorch, and could be fixed by substituting line 81 using the following code:
```Python
        if attention is not None:
```
